### ISSUE TITLE
RunEngine aborts due to missing module 'suitcase.mongo_normalized'

### ISSUE THREAD

**Issue by burkeds** [bluesky/bluesky#1551]
I am testing my Bluesky environment with simulated devices and a simple list_scan plan. The plan runs as expected until I try to subscribe the RunEngine to a catalog.

I subscribe the RunEngine to a catalog by doing:
`catalog = temp()`
`RE.subscribe(catalog.v1.insert)`

I then try and execute a plan:
`RE(list_scan(dets, motor1, [1,1,3]))`

When I do so, the run aborts with the following traceback. I have installed the latest databroker and suitcase-csv packages.

Run aborted
Traceback (most recent call last):
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/run_engine.py", line 1523, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/plans.py", line 177, in list_scan
    md=_md))
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/plans.py", line 1000, in scan_nd
    return (yield from inner_scan_nd())
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/utils/__init__.py", line 1147, in dec_inner
    return (yield from plan)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/preprocessors.py", line 952, in stage_wrapper
    return (yield from finalize_wrapper(inner(), unstage_devices()))
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/preprocessors.py", line 509, in finalize_wrapper
    ret = yield from plan
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/preprocessors.py", line 950, in inner
    return (yield from plan)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/utils/__init__.py", line 1147, in dec_inner
    return (yield from plan)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/preprocessors.py", line 317, in run_wrapper
    rs_uid = yield from open_run(md)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 824, in open_run
    return (yield Msg('open_run', **(md or {})))
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/run_engine.py", line 1583, in _run
    new_response = await coro(msg)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/run_engine.py", line 1774, in _open_run
    new_uid = await current_run.open_run(msg)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/bundlers.py", line 64, in open_run
    await self.emit(DocumentNames.start, doc)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/run_engine.py", line 2441, in emit
    self.emit_sync(name, doc)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/run_engine.py", line 2438, in emit_sync
    self.dispatcher.process(name, doc)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/run_engine.py", line 2461, in process
    exceptions = self.cb_registry.process(name, name.name, doc)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/utils/__init__.py", line 384, in process
    func(*args, **kwargs)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/bluesky/utils/__init__.py", line 473, in __call__
    return mtd(*args, **kwargs)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/databroker/v1.py", line 791, in insert
    self._serializer(name, doc)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/event_model/__init__.py", line 113, in __call__
    return self._dispatch(name, doc, validate)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/event_model/__init__.py", line 121, in _dispatch
    output_doc = getattr(self, name)(doc)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/event_model/__init__.py", line 1307, in start
    callbacks, subfactories = factory('start', start_doc)
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/databroker/v1.py", line 128, in factory
    return [self._catalog.get_serializer()], []
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/databroker/client.py", line 290, in get_serializer
    return tree.get_serializer()
  File "/opt/mambaforge/envs/cnbl/lib/python3.7/site-packages/databroker/mongo_normalized.py", line 1322, in get_serializer
    from suitcase.mongo_normalized import Serializer
ModuleNotFoundError: No module named 'suitcase.mongo_normalized'

**Comment by danielballan** [comment]
Please try

```
pip install suitcase-mongo
```

**Comment by burkeds** [comment]
Thank you. I installed it with mamba but that solved the problem. Was this required because I was using a temporary catalog?

**Comment by danielballan** [comment]
Any time you _save_ data with databroker you'll need that. There are some use cases where you only want to _read_ data that was already written, and then you could use databroker with suitecase-mongo.

In databroker 1.x (the current stable release) we are little fuzzy on this and maybe the conda recipe doesn't include suitecase-mongo.In databroker 2.x (in prerelease, not quite ready for wide use) things are clearer.

**Comment by burkeds** [comment]
Understood. Thank you.
