### ISSUE TITLE
Bluesky fails to properly recover from 'paused' state

### ISSUE THREAD

**Issue by dmgav** [bluesky/bluesky#1647]
Bluesky fails to properly recover from 'paused' state. Two different issues were noticed for 'immediate' and 'deferred' pause. Unit tests in Bluesky repository do not pick up the incorrect behavior. The issue was found while debugging failing Queue Server tests.

The issue was noticed with the standard `count` plan. The behavior may be different with other plans or custom plans.

```
In [9]: bluesky.__version__
Out[9]: '1.12.0+1.g9b0d7295'

In [10]: ophyd.__version__
Out[10]: '1.9.1.dev15+gc8847c8c'

In [11]: event_model.__version__
Out[11]: '0.1.dev919+g24661e3'
```

## Expected Behavior

Paused plan should resume using `RE.resume()` and continue execution of the plan.

## Current Behavior

1. Deferred pause (single Ctrl-C): in the `count` plan, first two measurement after resuming the plan are taken in rapid sequence, the following measurements are taken with the proper delay.
2. Immediate pause (double Ctrl-C): in the `count` plan, if the plan is paused during the first step (before the first step is completed), the plan is crashing with exception immediately after it is resumed.

## Steps to Reproduce (for bugs)

1 Activate the environment and start IPython.
2. Run the following code:
```
from bluesky import RunEngine
RE = RunEngine()

from bluesky.callbacks.best_effort import BestEffortCallback
bec = BestEffortCallback()
RE.subscribe(bec)

from ophyd.sim import det
from bluesky.plans import count
```

3. Issue with the 'deferred' pause. Run the following plan:
```
RE(count([det], num=5, delay=3)
```
Pause at any time with single Ctrl-C. Resume the plan with `RE.resume()`.  The first two steps will be executed in rapid sequence (without 3 second delay).

4. Issue with the 'immediate' pause. Run the same plan, then pause before the first step is completed with double Ctrl-C. Then resume with `RE.resume`. The plan crashes with exception:
```
In [2]: RE(count([det], num=5, delay=3))


Transient Scan ID: 1     Time: 2023-12-20 08:55:57
Persistent Unique Scan ID: '41de57ed-b0cf-4004-8517-494211544b72'
New stream: 'primary'
+-----------+------------+------------+
|   seq_num |       time |        det |
+-----------+------------+------------+
|         1 | 08:55:57.3 |      1.000 |
^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
^Ctrying a second time
Pausing...
---------------------------------------------------------------------------
RunEngineInterrupted                      Traceback (most recent call last)
Cell In[2], line 1
----> 1 RE(count([det], num=5, delay=3))

File ~/Projects/bluesky/bluesky/run_engine.py:906, in RunEngine.__call__(self, *args, **metadata_kw)
    903 plan_return = self._resume_task(init_func=_build_task)
    905 if self._interrupted:
--> 906     raise RunEngineInterrupted(self.pause_msg) from None
    908 if self._call_returns_result:
    909     run_engine_result = self._create_result(plan_return)

RunEngineInterrupted: 
Your RunEngine is entering a paused state. These are your options for changing
the state of the RunEngine:

RE.resume()    Resume the plan.
RE.abort()     Perform cleanup, then kill plan. Mark exit_stats='aborted'.
RE.stop()      Perform cleanup, then kill plan. Mark exit_status='success'.
RE.halt()      Emergency Stop: Do not perform cleanup --- just stop.


In [3]: RE.resume()
Run aborted
Traceback (most recent call last):
  File "/home/dgavrilov/Projects/bluesky/bluesky/run_engine.py", line 1532, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/home/dgavrilov/Projects/bluesky/bluesky/plans.py", line 82, in count
    return (yield from inner_count())
  File "/home/dgavrilov/Projects/bluesky/bluesky/utils/__init__.py", line 1203, in dec_inner
    return (yield from plan)
  File "/home/dgavrilov/Projects/bluesky/bluesky/preprocessors.py", line 985, in stage_wrapper
    return (yield from finalize_wrapper(inner(), unstage_devices()))
  File "/home/dgavrilov/Projects/bluesky/bluesky/preprocessors.py", line 535, in finalize_wrapper
    ret = yield from plan
  File "/home/dgavrilov/Projects/bluesky/bluesky/preprocessors.py", line 983, in inner
    return (yield from plan)
  File "/home/dgavrilov/Projects/bluesky/bluesky/utils/__init__.py", line 1203, in dec_inner
    return (yield from plan)
  File "/home/dgavrilov/Projects/bluesky/bluesky/preprocessors.py", line 351, in run_wrapper
    yield from contingency_wrapper(plan,
  File "/home/dgavrilov/Projects/bluesky/bluesky/preprocessors.py", line 606, in contingency_wrapper
    ret = yield from plan
  File "/home/dgavrilov/Projects/bluesky/bluesky/plans.py", line 79, in inner_count
    return (yield from bps.repeat(partial(per_shot, detectors),
  File "/home/dgavrilov/Projects/bluesky/bluesky/plan_stubs.py", line 1345, in repeat
    return (yield from repeated_plan())
  File "/home/dgavrilov/Projects/bluesky/bluesky/plan_stubs.py", line 1343, in repeated_plan
    yield Msg('sleep', None, d)
  File "/home/dgavrilov/Projects/bluesky/bluesky/run_engine.py", line 1507, in _run
    msg = self._plan_stack[-1].throw(stashed_exception or resp)
  File "/home/dgavrilov/Projects/bluesky/bluesky/utils/__init__.py", line 141, in <genexpr>
    gen = (msg for msg in gen)
  File "/home/dgavrilov/Projects/bluesky/bluesky/run_engine.py", line 1592, in _run
    new_response = await coro(msg)
  File "/home/dgavrilov/Projects/bluesky/bluesky/run_engine.py", line 1972, in _save
    await current_run.save(msg)
  File "/home/dgavrilov/Projects/bluesky/bluesky/bundlers.py", line 534, in save
    event_doc = compose_event(
  File "/home/dgavrilov/Projects/event-model/event_model/__init__.py", line 2326, in __call__
    seq_num = self.event_counters[self.descriptor["name"]]
KeyError: 'primary'
+-----------+------------+------------+
generator count ['41de57ed'] (scan num: 1)



---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[3], line 1
----> 1 RE.resume()

File ~/Projects/bluesky/bluesky/run_engine.py:949, in RunEngine.resume(self)
    947         fut = asyncio.run_coroutine_threadsafe(maybe_await(obj.resume()), self._loop)
    948         fut.result()
--> 949 plan_return = self._resume_task()
    950 if self._interrupted:
    951     raise RunEngineInterrupted(self.pause_msg) from None

File ~/Projects/bluesky/bluesky/run_engine.py:1042, in RunEngine._resume_task(self, init_func)
   1038 # if the main task exception is not None, re-raise
   1039 # it (unless it is a canceled error)
   1040 if (exc is not None
   1041         and not isinstance(exc, _RunEnginePanic)):
-> 1042     raise exc
   1043 # Only try to get a result if there wasn't an error,
   1044 # (other than a cancelled error)
   1045 if exc is None:

File ~/Projects/bluesky/bluesky/run_engine.py:1672, in RunEngine._run(self)
   1670     exit_reason = str(err)
   1671     self.log.exception("Run aborted")
-> 1672     raise err
   1673 finally:
   1674     if not exit_reason:

File ~/Projects/bluesky/bluesky/run_engine.py:1532, in RunEngine._run(self)
   1529 # The normal case of clean operation
   1530 else:
   1531     try:
-> 1532         msg = self._plan_stack[-1].send(resp)
   1533     # We have exhausted the top generator
   1534     except StopIteration:
   1535         # pop the dead generator go back to the top

File ~/Projects/bluesky/bluesky/plans.py:82, in count(detectors, num, delay, per_shot, md)
     78         yield from bps.declare_stream(*detectors, name='primary')
     79     return (yield from bps.repeat(partial(per_shot, detectors),
     80                                   num=num, delay=delay))
---> 82 return (yield from inner_count())

File ~/Projects/bluesky/bluesky/utils/__init__.py:1203, in make_decorator.<locals>.dec_outer.<locals>.dec.<locals>.dec_inner(*inner_args, **inner_kwargs)
   1201 plan = gen_func(*inner_args, **inner_kwargs)
   1202 plan = wrapper(plan, *args, **kwargs)
-> 1203 return (yield from plan)

File ~/Projects/bluesky/bluesky/preprocessors.py:985, in stage_wrapper(plan, devices)
    982     yield from stage_devices()
    983     return (yield from plan)
--> 985 return (yield from finalize_wrapper(inner(), unstage_devices()))

File ~/Projects/bluesky/bluesky/preprocessors.py:535, in finalize_wrapper(plan, final_plan, pause_for_debug)
    533 cleanup = True
    534 try:
--> 535     ret = yield from plan
    536 except GeneratorExit:
    537     cleanup = False

File ~/Projects/bluesky/bluesky/preprocessors.py:983, in stage_wrapper.<locals>.inner()
    981 def inner():
    982     yield from stage_devices()
--> 983     return (yield from plan)

File ~/Projects/bluesky/bluesky/utils/__init__.py:1203, in make_decorator.<locals>.dec_outer.<locals>.dec.<locals>.dec_inner(*inner_args, **inner_kwargs)
   1201 plan = gen_func(*inner_args, **inner_kwargs)
   1202 plan = wrapper(plan, *args, **kwargs)
-> 1203 return (yield from plan)

File ~/Projects/bluesky/bluesky/preprocessors.py:351, in run_wrapper(plan, md)
    348     else:
    349         yield from close_run(exit_status='fail', reason=str(e))
--> 351 yield from contingency_wrapper(plan,
    352                                except_plan=except_plan,
    353                                else_plan=close_run)
    354 return rs_uid

File ~/Projects/bluesky/bluesky/preprocessors.py:606, in contingency_wrapper(plan, except_plan, else_plan, final_plan, pause_for_debug, auto_raise)
    604 cleanup = True
    605 try:
--> 606     ret = yield from plan
    607 except GeneratorExit:
    608     cleanup = False

File ~/Projects/bluesky/bluesky/plans.py:79, in count.<locals>.inner_count()
     77 if predeclare:
     78     yield from bps.declare_stream(*detectors, name='primary')
---> 79 return (yield from bps.repeat(partial(per_shot, detectors),
     80                               num=num, delay=delay))

File ~/Projects/bluesky/bluesky/plan_stubs.py:1345, in repeat(plan, num, delay)
   1342             if d > 0:  # Sleep if and only if time is left to do it.
   1343                 yield Msg('sleep', None, d)
-> 1345 return (yield from repeated_plan())

File ~/Projects/bluesky/bluesky/plan_stubs.py:1343, in repeat.<locals>.repeated_plan()
   1341 d = d - (time.time() - now)
   1342 if d > 0:  # Sleep if and only if time is left to do it.
-> 1343     yield Msg('sleep', None, d)

File ~/Projects/bluesky/bluesky/run_engine.py:1507, in RunEngine._run(self)
   1504 if (stashed_exception is not None or isinstance(resp, Exception)):
   1505     # throw the exception at the current plan
   1506     try:
-> 1507         msg = self._plan_stack[-1].throw(stashed_exception or resp)
   1508     except Exception as e:
   1509         # The current plan did not handle it,
   1510         # maybe the next plan (if any) would like
   1511         # to try
   1512         self._plan_stack.pop()

File ~/Projects/bluesky/bluesky/utils/__init__.py:141, in <genexpr>(.0)
    138 gen = iter(plan)  # no-op on generators; needed for classes
    139 if not isinstance(gen, PLAN_TYPES):
    140     # If plan does not support .send, we must wrap it in a generator.
--> 141     gen = (msg for msg in gen)
    143 return gen

File ~/Projects/bluesky/bluesky/run_engine.py:1592, in RunEngine._run(self)
   1587 # try to finally run the command the user asked for
   1588 try:
   1589     # this is one of two places that 'async'
   1590     # exceptions (coming in via throw) can be
   1591     # raised
-> 1592     new_response = await coro(msg)
   1594 # special case `CancelledError` and let the outer
   1595 # exception block deal with it.
   1596 except asyncio.CancelledError:

File ~/Projects/bluesky/bluesky/run_engine.py:1972, in RunEngine._save(self, msg)
   1965 except KeyError as ke:
   1966     # sanity check -- this should be caught by 'create' which makes
   1967     # this code path impossible
   1968     raise IllegalMessageSequence(
   1969         "A 'save' message was sent but no " "run is open."
   1970     ) from ke
-> 1972 await current_run.save(msg)

File ~/Projects/bluesky/bluesky/bundlers.py:534, in RunBundler.save(self, msg)
    526 # Mark all externally-stored data as not filled so that consumers
    527 # know that the corresponding data are identifiers, not dereferenced
    528 # data.
    529 filled = {
    530     k: False
    531     for k, v in self._descriptors[desc_key].descriptor_doc["data_keys"].items()
    532     if "external" in v and v["external"] != "STREAM:"
    533 }
--> 534 event_doc = compose_event(
    535     data=data,
    536     timestamps=timestamps,
    537     filled=filled,
    538 )
    539 await self.emit(DocumentNames.event, event_doc)
    540 doc_logger.debug(
    541     "[event] document emitted with data keys %r (run_uid=%r)",
    542     data.keys(),
   (...)
    547         'data_keys': data.keys()}
    548 )

File ~/Projects/event-model/event_model/__init__.py:2326, in ComposeEvent.__call__(self, data, timestamps, seq_num, filled, uid, time, validate)
   2315 def __call__(
   2316     self,
   2317     data: dict,
   (...)
   2323     validate: bool = True,
   2324 ) -> Event:
   2325     if seq_num is None:
-> 2326         seq_num = self.event_counters[self.descriptor["name"]]
   2327     if uid is None:
   2328         uid = str(uuid.uuid4())

KeyError: 'primary'

```

**Comment by tacaswell** [comment]
My knee-jerk guess is that this is related to https://github.com/bluesky/bluesky/pull/1590

**Comment by tacaswell** [comment]
This bug only manifests if the pause is between the first and second points

A more minimal reproducer is

```python
import bluesky.preprocessors as bpp
import bluesky.plan_stubs as bps
from ophyd.sim import hw as _hw
from bluesky import RunEngine
from bluesky.callbacks.best_effort import BestEffortCallback

RE = RunEngine()
bec = BestEffortCallback()
RE.subscribe(bec)

hw = _hw()

@bpp.run_decorator()
def broken():
    yield from bps.checkpoint()
    yield from bps.trigger_and_read([hw.det])
    yield from bps.pause()
```

The issue is that on rewind we reset to the event counter dictionaries to the state before the check point.  If we implicitly (explictly adding `declare_stream` avoids the problem) create the stream after the checkpoint but before we pause then on resume we are missing the entry in `Bundler._event_counter` (which we in turn pass into the machinery of `EventModel` which is why the exception in coming from EventModel).  I will have a PR up shortly that fixes this.

**Comment by dmgav** [comment]
Part 2 of this issue is resolved in https://github.com/bluesky/bluesky/pull/1648
> Immediate pause (double Ctrl-C): in the count plan, if the plan is paused during the first step (before the first step is completed), the plan is crashing with exception immediately after it is resumed.

**Comment by dmgav** [comment]
Part 1 is not resolved yet.
