### ISSUE TITLE
Errors when passing in event loop to run-engine

### ISSUE THREAD

**Issue by evalott100** [bluesky/bluesky#1656]
In ophyd async, we'd like to be able to connect to devices before creating the `RunEngine` as [documented here](https://github.com/bluesky/ophyd-async/issues/112).

The goal would be to connect to our devices without a run engine:
``` python
    async with DeviceCollector(sim=True):
        sim_motor = motor.Motor("BLxxI-MO-TABLE-01:X")
```

Then use the run-engine when we want to:
``` python
    RE = RunEngine(loop=asyncio.get_running_loop())

    def my_plan():
        sim_motor.move(3.14)
        return

    RE(my_plan())

    assert await sim_motor.readback.get_value() == 3.14
```

We've come across a problem with the `RunEngine` loop argument:

``` python
from bluesky import RunEngine
import asyncio


async def coro ():
    loop = asyncio.get_event_loop()
    RunEngine(loop=loop)

asyncio.run(coro())
```

The above fails, with the stacktrace
```
Traceback (most recent call last):
  File "/scratch/twj43146/Programming/ophyd-async/test.py", line 9, in <module>
    asyncio.run(coro())
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/scratch/twj43146/Programming/ophyd-async/test.py", line 7, in coro
    RunEngine(loop=loop)
  File "/scratch/twj43146/Programming/ophyd-async/.venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 366, in __init__
    self._th = _ensure_event_loop_running(loop)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/twj43146/Programming/ophyd-async/.venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 2721, in _ensure_event_loop_running
    th = _ensure_event_loop_running.loop_to_thread[loop]
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.11/lib/python3.11/weakref.py", line 415, in __getitem__
    return self.data[ref(key)]
           ~~~~~~~~~^^^^^^^^^^
KeyError: <weakref at 0x7fdb76978a40; to '_UnixSelectorEventLoop' at 0x7fdb779b9dd0>
```

I wasn't able to find any tests for passing in a custom loop. We should add this functionality if it isn't already present.

@coretl @callumforrester

**Comment by callumforrester** [comment]
@tacaswell presume there just needs to be a check to see if the weakref has been collected and repopulate?

**Comment by evalott100** [comment]
The following works

``` python
def test_device_connector_async_run_engine_same_event_loop():
    async def set_up_device():
        async with DeviceCollector(sim=True):
            sim_motor = motor.Motor("BLxxI-MO-TABLE-01:X")
        return sim_motor

    loop = asyncio.new_event_loop()
    sim_motor = loop.run_until_complete(set_up_device())
    RE = RunEngine(loop=loop)

    def my_plan():
        yield from bps.mov(sim_motor, 3.14)

    RE(my_plan())

    async def get_setpoint():
        return await sim_motor.setpoint.read()

    assert asyncio.run(get_setpoint())["sim_motor-setpoint"]["value"] == 3.14
```
