### ISSUE TITLE
Rewrite the ZeroMQ tests to speed them up

### ISSUE THREAD

**Issue by callumforrester** [bluesky/bluesky#1690]
The [ZeroMQ tests](https://github.com/bluesky/bluesky/blob/main/src/bluesky/tests/test_zmq.py) are long-running system tests that slow down CI and local testing. They should be rewritten.

The current tests throw up and connect a ZeroMQ socket in a subprocess and then sleep for several seconds, waiting for it to start. This is very slow and potentially unreliable.

## Possible Solution
Some ideas:
- More functionality could be tested with mocking and unit-style tests, which are much faster
- There could be a single system test alonside the unit tests, to test against a real socket while minimizing the long-running tests
- Rather than kickoff in a subprocess and wait 5 seconds, could make use of a multiprocessing `Event` to synchronise on

**Comment by callumforrester** [comment]
In terms of acceptance criteria, I have run the ZMQ tests locally a few times (`tox -e tests -- src/bluesky/tests/test_zmq.py`) and they seem to take about 1:40 seconds to run on average, which is a long time! Ideally we want a few seconds but maybe 30s as a maximum.

**Comment by AlexanderWells-diamond** [comment]
One of the tests is also not doing cleanup properly, resulting in this rather unsightly message being printed in the middle of pytest's results:
```
src/bluesky/tests/test_zmq.py::test_zmq_components Exception ignored in: <function Context.__del__ at 0x7fd10671fb50>
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/zmq/sugar/context.py", line 136, in __del__
    warn(
ResourceWarning: Unclosed context <zmq.asyncio.Context() at 0x7fd09c200860>
Exception ignored in: <function Socket.__del__ at 0x7fd10671e5f0>
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/zmq/sugar/socket.py", line 179, in __del__
    warn(
ResourceWarning: Unclosed socket <zmq.asyncio.Socket(zmq.SUB) at 0x7fd09c1e6ce0>
Exception ignored in: <function Context.__del__ at 0x7fd10671fb50>
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/zmq/sugar/context.py", line 136, in __del__
    warn(
ResourceWarning: Unclosed context <zmq.asyncio.Context() at 0x7fd09c2009f0>
PASSED                                                                                                                                    [ 40%]
```

I wouldn't be surprised if this is actually happening in most of the tests, but we don't see it as it's happening in subprocesses.


p.s. code coverage should also be investigated here; `test_zmq_components` explicitly notes it exists because code coverage would miss the code in separate processes, but `pytest-cov` should cover this case and should already handle this for us. PErhaps [see here](https://pytest-cov.readthedocs.io/en/latest/subprocess-support.html)

**Comment by callumforrester** [comment]
Reviewers: @vshekar @callumforrester

**Comment by tacaswell** [comment]
https://github.com/bluesky/bluesky/pull/1672 has a fix for not closing resources.
